version: '3.1'

services:

  gateway:
    build: ./gateway
    ports:
      - '3000:3000'
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://root:root@db:27017
    depends_on:
      - orders
      - invoices

  orders:
    build: ./orders
    ports:
      - '3001:3001'
    environment:
      PORT: 3001
      MONGODB_URI: mongodb://root:root@db:27017
    depends_on:
      - db

  invoices:
    build: ./invoices
    ports:
      - '3002:3002'
    environment:
      PORT: 3002
      MONGODB_URI: mongodb://root:root@db:27017
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8082:8081'
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@db:27017/
    depends_on:
      - db
